# Generated by Django 5.1.1 on 2024-10-02 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('verano', 'Verano'), ('invierno', 'Invierno')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('enlace', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='outfits/')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armario.etiqueta')),
                ('pantalon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantalon', to='armario.prenda')),
                ('parte_arriba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parte_arriba', to='armario.prenda')),
                ('zapatos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zapatos', to='armario.prenda')),
            ],
        ),
    ]
